// Mock data cho LocalFood app
export const mockUser = {
  id: 1,
  username: 'localfood_vn',
  displayName: 'LocalFood VN',
  handle: '@localfood.vn',
  avatar: null,
  initials: 'LF',
  followers: 12400,
  following: 342,
  posts: 87,
};

export const mockStories = [
  { id: 1, name: 'Phở Hà Nội', emoji: '🍜', seen: false },
  { id: 2, name: 'Bún Bò', emoji: '🥩', seen: false },
  { id: 3, name: 'Bánh Mì', emoji: '🥖', seen: true },
  { id: 4, name: 'Cơm Tấm', emoji: '🍚', seen: false },
  { id: 5, name: 'Chả Cá', emoji: '🐟', seen: true },
  { id: 6, name: 'Gỏi Cuốn', emoji: '🥗', seen: false },
  { id: 7, name: 'Hủ Tiếu', emoji: '🍝', seen: true },
  { id: 8, name: 'Bún Chả', emoji: '🍖', seen: false },
];

export const mockPosts = [
  {
    id: 1,
    restaurantName: 'Phở Thìn Hà Nội',
    address: '13 Lò Đúc, Hai Bà Trưng, Hà Nội',
    category: 'Phở',
    emoji: '🍜',
    rating: 4.8,
    reviews: 1247,
    likes: 3842,
    liked: false,
    saved: false,
    priceRange: '35k–60k',
    tags: ['#phở', '#hanoi', '#streetfood', '#localfood'],
    description: 'Phở bò tái lăn - đặc sản của Phở Thìn với nước dùng đậm đà, thịt bò tươi ngon. Quán mở từ 6h sáng, thường có hàng dài nhưng xứng đáng để chờ!',
    commentsCount: 186,
    time: '2 giờ trước',
    colors: ['#ff7043', '#ff5722'],
    open: true,
  },
  {
    id: 2,
    restaurantName: 'Bún Bò Bà Tư',
    address: '26 Nguyễn Hữu Thọ, Quận 7, TP.HCM',
    category: 'Bún Bò',
    emoji: '🥣',
    rating: 4.6,
    reviews: 892,
    likes: 2156,
    liked: true,
    saved: true,
    priceRange: '45k–75k',
    tags: ['#bunbo', '#hue', '#saigon', '#authentic'],
    description: 'Bún bò Huế chính gốc với sả thơm, huyết heo và chả cua đặc trưng. Nước dùng cay vừa, đậm đà hương vị miền Trung. Quán nhỏ nhưng luôn đông khách.',
    commentsCount: 94,
    time: '5 giờ trước',
    colors: ['#e53935', '#c62828'],
    open: true,
  },
  {
    id: 3,
    restaurantName: 'Bánh Mì Huỳnh Hoa',
    address: '26 Lê Thị Riêng, Quận 1, TP.HCM',
    category: 'Bánh Mì',
    emoji: '🥖',
    rating: 4.9,
    reviews: 5631,
    likes: 9847,
    liked: false,
    saved: false,
    priceRange: '30k–55k',
    tags: ['#banhmi', '#iconic', '#musttry', '#saigon'],
    description: 'Bánh mì nổi tiếng nhất Sài Gòn! Ổ bánh giòn tan, nhân đầy ú với chả lụa, pate, trứng và rau thơm. Mở từ 3h chiều – 11h tối, hàng dài nhưng đáng đợi!',
    commentsCount: 423,
    time: '1 ngày trước',
    colors: ['#f9a825', '#f57f17'],
    open: false,
  },
  {
    id: 4,
    restaurantName: 'Cơm Tấm Thuận Kiều',
    address: '101 Trần Bình Trọng, Quận 5, TP.HCM',
    category: 'Cơm Tấm',
    emoji: '🍚',
    rating: 4.5,
    reviews: 672,
    likes: 1523,
    liked: false,
    saved: false,
    priceRange: '40k–80k',
    tags: ['#comtam', '#saigon', '#breakfast', '#sườn'],
    description: 'Cơm tấm sườn bì chả chuẩn vị Sài Gòn. Cơm dẻo mềm, sườn nướng thơm lừng, bì sợi giòn dai. Kèm nước mắm pha đặc trưng không nơi nào có.',
    commentsCount: 67,
    time: '2 ngày trước',
    colors: ['#6d4c41', '#4e342e'],
    open: true,
  },
];

export const mockSuggestions = [
  { id: 1, name: 'Ẩm Thực Đường Phố', handle: 'Gợi ý cho bạn', initials: '🌮', gradient: ['#ff6b35', '#f7c59f'], following: false },
  { id: 2, name: 'Quán Ăn Ngon HN', handle: 'Được theo dõi nhiều', initials: '🍜', gradient: ['#667eea', '#764ba2'], following: false },
  { id: 3, name: 'Saigon Food Tour', handle: 'Phổ biến gần bạn', initials: '🥗', gradient: ['#f093fb', '#f5576c'], following: true },
  { id: 4, name: 'Bếp Nhà Quê', handle: 'Gợi ý cho bạn', initials: '🍲', gradient: ['#4facfe', '#00f2fe'], following: false },
  { id: 5, name: 'Đồ Ăn Vặt SG', handle: 'Phổ biến trong khu vực', initials: '🍡', gradient: ['#43e97b', '#38f9d7'], following: false },
];

export const mockTrends = [
  { tag: '#phohaNoi', count: '14.2K bài viết' },
  { tag: '#banhmiSaigon', count: '9.8K bài viết' },
  { tag: '#streetfoodVN', count: '28.5K bài viết' },
  { tag: '#comtam', count: '7.3K bài viết' },
  { tag: '#bunbo', count: '11.1K bài viết' },
];

export const mockCategories = [
  { id: 'all', label: 'Tất cả', emoji: '🍽️' },
  { id: 'pho', label: 'Phở', emoji: '🍜' },
  { id: 'bun', label: 'Bún', emoji: '🥣' },
  { id: 'banh', label: 'Bánh', emoji: '🥖' },
  { id: 'com', label: 'Cơm', emoji: '🍚' },
  { id: 'lau', label: 'Lẩu', emoji: '🫕' },
  { id: 'cafe', label: 'Cà phê', emoji: '☕' },
  { id: 'trangtrang', label: 'Tráng miệng', emoji: '🍮' },
];

export const mockLocations = [
  {
    id: 1,
    name: 'Phở Thìn Hà Nội',
    lat: 21.0285, lng: 105.8048,
    category: 'Phở', emoji: '🍜',
    rating: 4.8, reviews: 1247,
    address: '13 Lò Đúc, Hai Bà Trưng, Hà Nội',
    priceRange: '35k–60k',
    open: true,
  },
  {
    id: 2,
    name: 'Chả Cá Lã Vọng',
    lat: 21.0335, lng: 105.8472,
    category: 'Chả Cá', emoji: '🐟',
    rating: 4.7, reviews: 892,
    address: '14 Chả Cá, Hoàn Kiếm, Hà Nội',
    priceRange: '150k–250k',
    open: true,
  },
  {
    id: 3,
    name: 'Bún Bò Bà Tư',
    lat: 10.7338, lng: 106.7022,
    category: 'Bún Bò', emoji: '🥩',
    rating: 4.6, reviews: 672,
    address: '26 Nguyễn Hữu Thọ, Quận 7, TP.HCM',
    priceRange: '45k–75k',
    open: false,
  },
];

export const mockDetailLocation = {
  id: 1,
  name: 'Phở Thìn Hà Nội',
  address: '13 Lò Đúc, Hai Bà Trưng, Hà Nội',
  category: 'Phở',
  emoji: '🍜',
  rating: 4.8,
  reviews: 1247,
  likes: 3842,
  followers: 412,
  priceRange: '35k–60k',
  phone: '024 3825 0896',
  website: 'phothinha.com.vn',
  description: 'Phở Thìn nổi tiếng với món phở bò tái lăn đặc biệt – thịt bò được xào nhanh trên lửa lớn trước khi cho vào tô. Nước dùng hầm từ xương bò nhiều giờ, trong vắt và đậm đà.',
  open: true,
  images: ['🍜', '🔥', '🥩', '⭐'],
  foods: [
    { id: 1, name: 'Phở Tái Lăn', price: '55.000đ', emoji: '🍜' },
    { id: 2, name: 'Phở Gầu', price: '55.000đ', emoji: '🥩' },
    { id: 3, name: 'Phở Đặc Biệt', price: '65.000đ', emoji: '⭐' },
    { id: 4, name: 'Quẩy (Phần)', price: '10.000đ', emoji: '🥐' },
  ],
  hours: [
    { day: 'Thứ 2', time: '6:00 – 10:00', today: false },
    { day: 'Thứ 3', time: '6:00 – 10:00', today: false },
    { day: 'Thứ 4', time: '6:00 – 10:00', today: false },
    { day: 'Thứ 5', time: '6:00 – 10:00', today: false },
    { day: 'Thứ 6', time: '6:00 – 10:00', today: false },
    { day: 'Thứ 7', time: '6:00 – 11:00', today: true },
    { day: 'Chủ Nhật', time: '6:00 – 11:00', today: false },
  ],
  reviews: [
    { id: 1, username: 'foodie_hanoi', rating: 5, comment: 'Phở ngon nhất Hà Nội tôi từng ăn! Nước dùng đậm đà, thịt mềm. Nhất định phải thử!', time: '2 giờ trước' },
    { id: 2, username: 'traveler_vn', rating: 4, comment: 'Quán khá nhỏ và đông, nhưng đồ ăn rất ngon và phục vụ nhanh. Giá cả hợp lý.', time: '1 ngày trước' },
    { id: 3, username: 'saigon_eater', rating: 5, comment: 'Đã ăn nhiều chỗ nhưng phở ở đây đặc biệt hơn hẳn nhờ cách xào thịt trực tiếp.', time: '3 ngày trước' },
  ],
};
