spring:
  application:
    name: LocalFood Backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/doiquadi}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:142857}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      exclude: static/**,public/**

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.localfood: DEBUG
